# Generated by Django 5.2.5 on 2025-08-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
